version: "3"

services:
  apigraphql:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: apigraphql
    restart: always
    ports: 
      - "3000:3000"
    links:
      - mongo
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    networks:
      - apigraph-network
  
  mongo:
    image: mongo
    container_name: mongodb
    restart: always
    ports: 
      - "27017:27017"
    volumes:  
      - dbdata:/data/db
    logging:
        driver: none
    networks:
      - apigraph-network

networks:
  apigraph-network:
    driver: bridge

volumes:
  dbdata:
  node_modules:  
